name: Auto Devops QA Merge

on:
  pull_request:
    branches:
      - master
    types:
      - opened
  pull_request_review:
    types:
      - submitted
    check_suite:
      types:
        - completed
    status: { }

jobs:
  automerge:
    runs-on: ubuntu-latest
    steps:
      #      - id: approve
      #        name: Approve Pull Request
      #        uses: juliangruber/approve-pull-request-action@v2.0.0
      #        with:
      #          github-token: ${{secrets.AUTOMERGE}}
      #          number: ${{ github.event.pull_request.number }}

      # DO QA AUTO-MERGE ===============================================================================================
      - id: automerge
        name: Merge Pull Request
        if: ${{ startsWith(github.event.pull_request.title, vars.REQ) }}
        uses: juliangruber/merge-pull-request-action@v1
        with:
          github-token: ${{ secrets.AUTOMERGE }}
          number: ${{ github.event.pull_request.number }}
          method: merge

      # FEEDBACK IF PULL REQUEST REQUIREMENT/US/HU IS INCORRECT ========================================================
      - id: reject
        name: Feedback - Validation if rejected
        if: ${{ !startsWith(github.event.pull_request.title, vars.REQ) }}
        uses: peter-evans/close-pull@v3
        with:
          token: ${{ secrets.AUTOMERGE }}
          pull-request-number: ${{ github.event.pull_request.number }}
          comment: Pull request rechazado porque la estructura del título no es "${{ vars.REQ }} - Descripción".
          delete-branch: false

      # FEEDBACK IF PULL REQUEST WAS MERGED ============================================================================
      - name: Feedback - Merged
        run: |
          echo "Pull request #${{ github.event.pull_request.number }} for requirement ${{ vars.REQ }} merged!"
          echo "${{toJson(github)}}"


