name: Auto Devops QA Merge

on:
  pull_request:
    branches:
      - master
    types:
      - opened

jobs:
  automerge:
    runs-on: ubuntu-latest
    steps:
      - id: automerge
        name: automerge
        uses: "pascalgn/automerge-action@v0.15.6"
        env:
          GITHUB_TOKEN: "${{secrets.AUTOMERGE}}"
          LOG: "TRACE"
      - name: feedback
        # if: steps.automerge.outputs.mergeResult == "merged"
        run: |
          echo "${{ steps.automerge.outputs.mergeResult }}!"
          echo "Pull request ${{ steps.automerge.outputs.pullRequestNumber }} merged!"

