name: Auto Devops QA Merge

on:
  pull_request:
    branches:
      - master
    types:
      - opened
  pull_request_review:
    types:
      - submitted
    check_suite:
      types:
        - completed
    status: { }

jobs:
  automerge:
    runs-on: ubuntu-latest
    steps:
      #      - id: approve
      #        name: Approve Pull Request
      #        uses: juliangruber/approve-pull-request-action@v2.0.0
      #        with:
      #          github-token: ${{secrets.AUTOMERGE}}
      #          number: ${{ github.event.pull_request.number }}

      # DO QA AUTO-MERGE ===============================================================================================
      - id: automerge
        name: Merge Pull Request
        if: ${{startsWith(github.event.pull_request.title, vars.REQ)}}
        uses: juliangruber/merge-pull-request-action@v1
        with:
          github-token: ${{secrets.AUTOMERGE}}
          number: ${{ github.event.pull_request.number }}
          method: merge

      # FEEDBACK IF PULL REQUEST REQUIREMENT/US/HU IS INCORRECT ========================================================
      - id: reject
        name: Feedback - Validation if rejected
        if: ${{!startsWith(github.event.pull_request.title, vars.REQ)}}
        uses: superbrothers/close-pull-request@v3
        with:
          comment: "Pull request rechazado porque no cuenta con la estructura requerida para su aprobación"

      # FEEDBACK IF PULL REQUEST WAS MERGED ============================================================================
      - name: Feedback - Merged
        if: ${{github.event.pull_request.merged}}
        run: |
          echo "Pull request #${{github.event.pull_request.number}} for requirement ${{vars.REQ}} merged!"


