name: Auto Devops QA Merge

on:
  pull_request:
    branches:
      - master
    types:
      - opened
  pull_request_review:
    types:
      - submitted
    check_suite:
      types:
        - completed
    status: {}

jobs:
  automerge:
    runs-on: ubuntu-latest
    steps:
      - id: automerge
        name: Merge Pull Request
        uses: juliangruber/merge-pull-request-action@v1
        with:
          github-token: ${{secrets.AUTOMERGE}}
          number: 9

